[profile.default]
src = 'contracts'
out = 'foundry-out'
optimizer_runs = 800
via_ir = false
ffi = true
fs_permissions = [{ access = "read-write", path = ".forge-snapshots/"}, { access = "read", path = "./foundry-out"}]
cancun = true
solc = "./bin/solc"

[profile.ci]
fuzz_runs = 100000
solc = "./bin/solc-static-linux"
cancun = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
