[default]
src = 'contracts'
out = 'foundry-out'
solc_version = '0.8.15'
optimizer_runs = 800

[ci]
fuzz_runs = 100000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config